# App
spring.application.name=liquidity-orchestrator

# PostgreSQL (use your online DB URL here)
spring.datasource.url=jdbc:postgresql://db.zofsebbdjtvztzfjzuzt.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=B_Y#7v$yBT2mWwk
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Neo4j (Aura)
spring.neo4j.uri=neo4j+s://aaba0634.databases.neo4j.io
spring.neo4j.authentication.username=aaba0634
spring.neo4j.authentication.password=KF-pUef0I6_EA7m7XB1yPRv7BDsdg1taxi6UFoLtSfs
spring.jpa.open-in-view=false
# JWT
jwt.secret=your-super-secret-key-must-be-at-least-256-bits-long-for-security
jwt.expiration=86400000

# Server port
server.port=8081

# CORS
spring.web.cors.allowed-origins=http://localhost:5173